name: csvloader
description: Simple, cross-platform Dart class to read  CSV data from a `Stream`. Supports and extends RFC 4180.
version: 1.0.0
homepage: https://github.com/d-markey/csvloader

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
