name: csvloader
description: Simple, cross-platform Dart class to read  CSV data from a `Stream`. Supports and extends RFC 4180.
version: 1.1.0
homepage: https://github.com/d-markey/csvloader

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
